### ISSUE TITLE
可以分享一下代码吗

### ISSUE THREAD

**Issue by HELLOWORLD1030** [BUPT-GAMMA/IGM#2]
您好，我看了您在AAAI上发表的文章，对我很有帮助，可以麻烦，分享一下代码吗，不胜感激，谢谢

**Comment by yiyi1333** [comment]
您好，我也看到了您在AAAI上的文章，对我非常有启发，可以分享一下代码吗，感谢！

**Comment by liuxinyi1202** [comment]
您好，我也看到了您在AAAI上的文章，对我非常有启发，可以分享一下代码吗，感谢！

**Comment by yiyi1333** [comment]
您的邮件yiyi已收到！

**Comment by Cloud-Minor** [comment]
您好，我也看到了您在AAAI上的文章，对我非常有启发，可以分享一下代码吗，感谢！

**Comment by wangys102** [comment]
您好，我也看到了您在AAAI上的文章，对我非常有启发，可以分享一下代码吗，感谢！
